### ISSUE TITLE
pod networking

### ISSUE THREAD

**Issue by glaszig** [smlloyd/ansible-role-minio_podman#5]
what do you think about putting the container into a dedicated podman pod?

background: i was trying to use the [minio/mc](https://registry.hub.docker.com/r/minio/mc) container to do some administration tasks but that fails because that container currently has no access to the minio server container. putting the server container inside a pod and running minio/mc inside that same pod allows (at least according to [the docs](https://www.redhat.com/sysadmin/container-networking-podman)) both to communicate easily.

**Comment by glaszig** [comment]
upgrade path: for users which are currently running minio by way of this role i have no idea right now how to handle that. as far as i have read there's no way to move an existing container into a pod.

**Comment by smlloyd** [comment]
That actually seemed like a good idea to me when I initially made this. It's been a while, but if I remember correctly I think the reason why I didn't put it in a pod was because podman could only generate systemd files for containers, and not pods (on centos, at least).

**Comment by glaszig** [comment]
i _think_ you'll need a seperate systemd unit for every container in a pod anyway. the unit file just starts and stops a container by name. everything else is handled by podman and the pod association is part of a containers meta data. see the following podman-generated unit file.

```
# container-minio.service
# autogenerated by Podman 1.6.4
# Sat Feb 27 01:10:35 CET 2021

[Unit]
Description=Podman container-minio.service
Documentation=man:podman-generate-systemd(1)

[Service]
Restart=always
ExecStart=/usr/bin/podman start minio
ExecStop=/usr/bin/podman stop -t 5 minio
KillMode=none
Type=forking
PIDFile=/var/run/containers/storage/overlay-containers/fa86949dffd94c32aef2a3809e1b2383bf548eb954d244ee737fae348864fdc8/userdata/conmon.pid

[Install]
WantedBy=multi-user.target
```

**Comment by smlloyd** [comment]
Indeed you do. It was more about autogenerating those systemd files - back when I made this role that wasn't implemented for pods in the podman version shipped with Centos, and I didn't want to muck about with templates. It seems to be implemented now, so that reason is gone.

I think putting a minio container in a pod alongside an optional mc container could be neat. I'm guessing the mc container wouldn't even need a systemd file?

**Comment by glaszig** [comment]
> didn't want to muck about with templates

understood.

> the mc container wouldn't even need a systemd file?

correct. i would like to use minio/mc to create accounts and policies as part of my ansible playbook.

do you care about backward-compat? though for existing systems everything should continue to work. only if/when the container gets (re)created it would get put into a minio-pod...

**Comment by smlloyd** [comment]
> do you care about backward-compat? though for existing systems everything should continue to work. only if/when the container gets (re)created it would get put into a minio-pod...

Agreed. I reckon the switch would be fairly transparent. Only obvious difference I can think of right now might be a change in service name from container-minio to pod-minio.
